# Generated by Django 5.2.8 on 2026-06-06 12:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(choices=[('qwerty', 'QWERTY'), ('jcuken', 'ЙЦУКЕН')], db_index=True, max_length=10, verbose_name='Keyboard Layout')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('content', models.TextField(verbose_name='Content to Type')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['layout', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], db_index=True, max_length=2, verbose_name='Language')),
                ('test_type', models.CharField(choices=[('words', 'Words'), ('time', 'Time')], db_index=True, max_length=10, verbose_name='Test Type')),
                ('word_count', models.PositiveSmallIntegerField(blank=True, choices=[(10, '10'), (25, '25'), (50, '50'), (100, '100')], null=True, verbose_name='Word Count')),
                ('time_limit', models.PositiveSmallIntegerField(blank=True, choices=[(15, '15s'), (30, '30s'), (60, '60s'), (120, '120s')], null=True, verbose_name='Time Limit (s)')),
                ('wpm', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='WPM')),
                ('cpm', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='CPM')),
                ('accuracy', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Accuracy (%)')),
                ('typos', models.PositiveIntegerField(default=0, verbose_name='Typos')),
                ('duration', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Duration (s)')),
                ('is_record', models.BooleanField(default=False, verbose_name='Personal Record')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Test Result',
                'verbose_name_plural': 'Test Results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'language', 'test_type'], name='core_testre_user_id_422d1e_idx'), models.Index(fields=['user', 'created_at'], name='core_testre_user_id_5dfc37_idx')],
            },
        ),
    ]
