# Generated by Django 5.2.8 on 2026-06-07 10:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], db_index=True, max_length=2, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('key_combination', models.CharField(help_text='e.g. "asdf" for English or "фыва" for Russian', max_length=50, verbose_name='Key Combination')),
                ('content', models.TextField(help_text='Sequence of words separated by single spaces. No punctuation. English: a-z only. Russian: а-я/ё only.', verbose_name='Content')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['language', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], db_index=True, max_length=2, verbose_name='Language')),
                ('word_count', models.PositiveSmallIntegerField(choices=[(10, '10'), (25, '25'), (50, '50'), (100, '100')], db_index=True, verbose_name='Word Count')),
                ('wpm', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='WPM')),
                ('cpm', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='CPM')),
                ('accuracy', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Accuracy (%)')),
                ('typos', models.PositiveIntegerField(default=0, verbose_name='Typos')),
                ('duration', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Duration (s)')),
                ('is_record', models.BooleanField(default=False, verbose_name='Personal Record')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Test Result',
                'verbose_name_plural': 'Test Results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'language', 'word_count'], name='core_testre_user_id_3cdffa_idx')],
            },
        ),
    ]
