# Generated by Django 5.2.8 on 2026-06-02 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['user', 'language', 'test_type'], name='core_testre_user_id_422d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['user', 'created_at'], name='core_testre_user_id_5dfc37_idx'),
        ),
    ]
